//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rólunk.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Felület.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználási tertület.
        /// </summary>
        public static string AreaOfUsage {
            get {
                return ResourceManager.GetString("AreaOfUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galéria Kategóriák.
        /// </summary>
        public static string CategoriesInGallery {
            get {
                return ResourceManager.GetString("CategoriesInGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegyianyagok.
        /// </summary>
        public static string Chemicals {
            get {
                return ResourceManager.GetString("Chemicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapcsolatok.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapcsolatok.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.CSV file.
        /// </summary>
        public static string CsvFile {
            get {
                return ResourceManager.GetString("CsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Részletek.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerkesztés.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válasszon kategóriát a termékek megjelenítéséhez..
        /// </summary>
        public static string EmptyProductTable {
            get {
                return ResourceManager.GetString("EmptyProductTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Műtrágya.
        /// </summary>
        public static string Fertilizer {
            get {
                return ResourceManager.GetString("Fertilizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galéria.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék Importálás.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integráció.
        /// </summary>
        public static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főkategória.
        /// </summary>
        public static string MainCategoryLabel {
            get {
                return ResourceManager.GetString("MainCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyártó.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hírek.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hír Kategóriák.
        /// </summary>
        public static string NewsCategories {
            get {
                return ResourceManager.GetString("NewsCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bővebben....
        /// </summary>
        public static string NewsDetails {
            get {
                return ResourceManager.GetString("NewsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Növényvédő szerek.
        /// </summary>
        public static string Pesticides {
            get {
                return ResourceManager.GetString("Pesticides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Származási hely.
        /// </summary>
        public static string PlaceOfOrigin {
            get {
                return ResourceManager.GetString("PlaceOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék Kategóriák.
        /// </summary>
        public static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termékek.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minőség.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mennyiség.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vetőmagok.
        /// </summary>
        public static string Seeds {
            get {
                return ResourceManager.GetString("Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szolgáltatások.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkategória.
        /// </summary>
        public static string SubCategoryLabel {
            get {
                return ResourceManager.GetString("SubCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termény-kereskedelem.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Típus.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiszerelés.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiszerelések.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltöltés.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználók.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
